apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
        - name: springboot
          image: scm-springboot:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: MYSQL_HOST
              value: "mysql"
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DB
              value: "scm20"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: "root1234"
            - name: EMAIL_HOST
              value: "smtp.gmail.com"
            - name: EMAIL_PORT
              value: "587"
            - name: EMAIL_USERNAME
              value: "batchlcwd@gmail.com"
            - name: EMAIL_PASSWORD
              value: "dqwxmxfvukvwhnkh"
            - name: EMAIL_DOMAIN
              value: "batchlcwd@gmail.com"
            - name: CLOUDINARY_API_KEY
              value: "575233445171369"
            - name: CLOUDINARY_API_SECRET
              value: "WF88TQpJyKATyZCv4o4M0dx3xEQ"
            - name: CLOUDINARY_NAME
              value: "derpgrwbe"
---
apiVersion: v1
kind: Service
metadata:
  name: springboot
spec:
  selector:
    app: springboot
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort
